include stdio.h in hocdec.h
compilation with gcc >= 7 can fail with

    oc_ansi.h:109:24: error: unknown type name 'FILE'

due to stdio.h not being included.
There is a conditional include of stdio.h in hocassrt.h that may be related.