Fix some ctest errors. (#752)
When -DNRN_ENABLE_PYTHON_DYNAMIC=ON ctest may run nrniv from
CMAKE_PROJECT_BUILD/bin and that may need a copy of nrnpyenv.sh
there as well.

ctest can exhibit the error:
SyntaxError: unqualified exec is not allowed in function 'e' because it
is a nested function (test_basic.py, line 87)