Additional Fixes for windows build with CMake and setup.py (#256)
* (WIP) Fixes for windows build with CMake
  It now builds till nrniv.so:
    kumbhar@DESKTOP-A627701 MSYS ~/nrn/build
    $ make
    [  6%] Built target nocmodl
    [  9%] Built target modlunit
    Scanning dependencies of target nrniv_lib
    [  9%] Building C object src/nrniv/CMakeFiles/nrniv_lib.dir/__/oc/cygwinprt.c.obj
    [ 10%] Linking CXX shared library libnrniv.so
    CMakeFiles/nrniv_lib.dir/__/nrnoc/init.c.obj: In function `hoc_last_init':
    C:/msys64/home/kumbhar/nrn/src/nrnoc/init.c:351: undefined reference to `modl_reg'
    collect2.exe: error: ld returned 1 exit status
    make[2]: *** [src/nrniv/CMakeFiles/nrniv_lib.dir/build.make:6422: src/nrniv/libnrniv.so] Error 1
    make[1]: *** [CMakeFiles/Makefile2:181: src/nrniv/CMakeFiles/nrniv_lib.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
* Add missing termcap module
  - find termcap before adding nrniv folder
  - do not link to libdl on mingw platform
* Various to make NEURON buildable under windows:
  - make cmake option consistent for shared library
  - replace find command with CMake's find(GLOB_RECURSE..
    so that it becomes windows compatiable (find.exe has different
    options than *nix)
  - link stnadard libc and libc++ in static mode for mingw/windows build
  - use setup.cfg to tell distutils to use mingw toolchain instead of
    visual studio
  - setup.py is updated to translate C:/msys64 to C:\\msys64 so that
    windows python understand paths correctly
  - adjust python install --home argument for windows
* More cmake cleanup (#260)
* Added missing dependency rules
* Fixed outstanding issue with cmake config files
* Moved nrnivmodl makefile generator to right dir.
* Windows InterViews does not need X11 and backslash needs escape.
* With MINGW -DNRN_ENABLE_INTERVIEWS kind of works.
* CMAKE_INSTALL_BINDIR and others did not get set.
* Cmake MATCHES to STREQUAL as "" matches anything.
* Only add python interface to libnrniv if not dynamic and python enabled
* WIP for NRN_ENABLE_PYTHON_DYNAMIC for MINGW
    MINGW libnrnpython needs to link against libpython to avoid
    undeclared names. So introduce libnrnpython<major><minor> library targets
    for each python in the NRN_PYTHON_DYNAMIC list if LINK_AGAINST_PYTHON
    is ON (now hardwired as ON in PythonDynamicHelper.cmake for
    development on MAC but only needed for MINGW). Currently what is missing
    is for nrnpy.cpp to figure out <major><minor> suffix when nrniv is launched.
* Proper permissions for installed scripts.
* When launch nrniv, calculate libnrnpython name from python library.
* MINGW python dynamic loading fixes
* USE_LIBNRNPYTHON_MAJORMINOR needs to be 1 or 0 for #define
* Cmake build report enhancement and cleanup (#274)
* CMake cleanup with build report
* Add NEURON_INIT_MPI possibilities when dynamic loading MPI (#261)
  - If NEURON_INIT_MPI==0 dont load MPI library; else load MPI
* mkdir with MINGW takes only one arg.

Co-authored-by: Pramod Kumbhar <pramod.kumbhar@epfl.ch>
Co-authored-by: Michael Hines <michael.hines@yale.edu>