Fix race condition in CMake code. (#3198)
There's a race condition to create `parse1.cpp` (and other files). One
way we can see there's an issue is by looking that the output of
`cmake --build ... --parallel` (reordered):
```
[  0%] [BISON][modlunitparser] Building parser with bison 3.8.2
[  3%] [BISON][modlunitparser] Building parser with bison 3.8.2

[  1%] [FLEX][modlunitlexer] Building scanner with flex 2.6.4
[  3%] [FLEX][modlunitlexer] Building scanner with flex 2.6.4

[  0%] [BISON][nocmodlparser] Building parser with bison 3.8.2
[  1%] [BISON][nocmodlparser] Building parser with bison 3.8.2
[  3%] [BISON][nocmodlparser] Building parser with bison 3.8.2
[  3%] [BISON][nocmodlparser] Building parser with bison 3.8.2

[  1%] [FLEX][nocmodllexer] Building scanner with flex 2.6.4
[  3%] [BISON][ocparser] Building parser with bison 3.8.2
```
what we see is that `[nocmodlparser] Building parser` happens 4
times. Each file should only be generated once. The situation is
slightly misleading, because there's 2 `add_custom_command`s that
use the same description string. Therefore, we'd expect to see two
such lines, but not 4.

Similarly, `[modlunitparser] Building parser` should only happen once.

The other way we can see the issue is by compiling repeatedly until we
get a:
```
src/nrniv/nocmodl_generated/parse1.cpp:209:32: error: expected identifier at end of input
src/nrniv/nocmodl_generated/parse1.cpp:209:32: error: expected ‘}’ at end of input
src/nrniv/nocmodl_generated/parse1.cpp:163:1: note: to match this ‘{’
src/nrniv/nocmodl_generated/parse1.cpp:209:32: error: expected unqualified-id at end of input
```

After the changes I ran:
```
$ cat detect_race.sh
set -e
for i in $(seq 20)
do
  rm build-integrate -r; cmake -DCMAKE_INSTALL_PREFIX=build-integrate/install -DNRN_ENABLE_PYTHON=ON -DNRN_ENABLE_TESTS=ON -DNRN_ENABLE_DOCS=OFF -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_BACKTRACE=ON -DNRN_ENABLE_RX3D=OFF -DNRN_ENABLE_MPI_DYNAMIC=OFF -DCMAKE_BUILD_TYPE=Debug -DNRN_ENABLE_NMODL=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=On -B build-integrate . && cmake --build build-integrate --parallel --target=install
done
```
(which used to error on the first iteration.) The log contains (sorted to
match the above):
```
[  3%] [BISON][modlunitparser] Building parser with bison 3.8.2

[  2%] [FLEX][modlunitlexer] Building scanner with flex 2.6.4

[  3%] [BISON][nocmodlparser] Building parser with bison 3.8.2
[  5%] [BISON][nocmodlparser] Building diffeq with bison 3.8.2

[  4%] [FLEX][nocmodllexer] Building scanner with flex 2.6.4
[  5%] [BISON][ocparser] Building parser with bison 3.8.2
```