Set missing IV_LIBDIR (#254)
* Set missing IV_LIBDIR

* Add missing rpath for interviews lib directory

* Small changes while testing on Ubuntu
  - print python include directory (which could be missing)
  - check python dir exist to avoid comple time error

* Fix missing linking with -lpthread and -ldl with dynamic mpi and python
on linux

[ 98%] Linking CXX executable ../../bin/nrniv
[ 98%] Building CXX object src/nrnpython/CMakeFiles/nrnpython3.dir/nrnpy_p2h.cpp.o
libnrniv.so: undefined reference to `pthread_create'
libnrniv.so: undefined reference to `dlopen'
libnrniv.so: undefined reference to `dlclose'
libnrniv.so: undefined reference to `dlerror'
libnrniv.so: undefined reference to `dlsym'
libnrniv.so: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status

* Fix issue with python dynamic support is enabled

  - I see below error when trying to use python dynamic build:
    ```
    nrn/install-dir/x86_64/bin/nrniv -python -pyexe python3.7 -c 'import neuron ; neuron.test() ;'
    NEURON -- VERSION 7.7.1-24-g4524ea3c master (4524ea3c) 2019-07-31
    Duke, Yale, and the BlueBrain Project -- Copyright 1984-2018
    See http://neuron.yale.edu/neuron/credits

    bash: nrnpyenv.sh: No such file or directory
    Python not available
    ```

  - This is because popen fails for `bash nrnpyenv.sh` fails.

* Install nrnpyenv.sh to install-prefix/bin