Additional Fixes for windows build with CMake and setup.py (#256)
* (WIP) Fixes for windows build with CMake

This is still WIP and builds up to Python.

* More fixes for windows build. Some are temporary ones.

It now builds till nrniv.so:

kumbhar@DESKTOP-A627701 MSYS ~/nrn/build
$ make
[  6%] Built target nocmodl
[  9%] Built target modlunit
Scanning dependencies of target nrniv_lib
[  9%] Building C object src/nrniv/CMakeFiles/nrniv_lib.dir/__/oc/cygwinprt.c.obj
[ 10%] Linking CXX shared library libnrniv.so
CMakeFiles/nrniv_lib.dir/__/nrnoc/init.c.obj: In function `hoc_last_init':
C:/msys64/home/kumbhar/nrn/src/nrnoc/init.c:351: undefined reference to `modl_reg'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/nrniv/CMakeFiles/nrniv_lib.dir/build.make:6422: src/nrniv/libnrniv.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:181: src/nrniv/CMakeFiles/nrniv_lib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

* Add missing termcap module

* Additional windows fixes:
  - find termcap before adding nrniv folder
  - do not link to libdl on mingw platform

* Various to make NEURON buildable under windows:
  - make cmake option consistent for shared library
  - replace find command with CMake's find(GLOB_RECURSE..
    so that it becomes windows compatiable (find.exe has different
    options than *nix)
  - link stnadard libc and libc++ in static mode for mingw/windows build
  - use setup.cfg to tell distutils to use mingw toolchain instead of
    visual studio
  - setup.py is updated to translate C:/msys64 to C:\\msys64 so that
    windows python understand paths correctly
  - adjust python install --home argument for windows