Avoid duplicating `acc --oacc` arguments to NMODL (BlueBrain/CoreNeuron#486)
* Avoid duplicating 'acc --oacc' arguments to NMODL.
    - When both CORENRN_ENABLE_NMODL and CORENRN_ENABLE_GPU
       are true then these arguments were added twice, which triggers a compilation error:
           file: File does not exist: acc
* fix ringtest : spike outputes are now written in current directory and use option -dumpmodel

CoreNEURON Repo SHA: BlueBrain/CoreNeuron@da98ae6bbf8ed5313bcea1dc62c56cfa55751599