Allow to run clang-format on nocmodl generated C++ files (#2542)
With the current master if we run clang-format on generated file
and try to rebuild then we get errors like

```
src/nrnoc/netstim.cpp:393:28: error: no member named '_prop' in 'Point_process'; did you mean 'prop'?
    auto* const _p = _pnt->_prop;
```

This is because we have some magic header macros that rename certain
internal variables.

To avoid the issue, just tell clang-format to avoid sorting headers
included.