Pin tenacity package (plotly dep)
The CI here:
https://github.com/neuronsimulator/nrn/actions/runs/9543904495/job/26301425761
is failing with the error:

  ModuleNotFoundError: No module named 'tenacity.asyncio'

This is probably due to a new version of tenacity being released:

  https://github.com/jd/tenacity/compare/8.3.0...8.4.0

So until plotly fixes it on their end, we explicitly pin it ourselves.