Pin numpy max version to <2, pin tenacity package (plotly dep) (#2916)
* Pin numpy max version to <2
* Pin version of numpy in CI
* Pin tenacity package (plotly dep)
      - The CI here: https://github.com/neuronsimulator/nrn/actions/runs/9543904495/job/26301425761 is failing with the error:
          ModuleNotFoundError: No module named 'tenacity.asyncio'
      - This is probably due to a new version of tenacity being released:
            https://github.com/jd/tenacity/compare/8.3.0...8.4.0