Undefined reference to `solve_core' (BlueBrain/CoreNeuron#430)
* Fixing missing dependency in the makefile target
* enginemch.o is needed before creation of shared/static library libcorenrnmech created

CoreNEURON Repo SHA: BlueBrain/CoreNeuron@fa5744fb3ce0b70eff1129e20d34f36c4dd1fa08