enhanced comparison of NEURON objects (#71)
* enhanced comparison of NEURON objects

(previously comparison only worked for HocObjects, Sections, and Segments)

                          Test      Value  Expected  Result
-----------------------------------------------------------
                          a==a       True      True  passed
                          a==b      False     False  passed
                          a!=b       True      True  passed
                          d==c       True      True  passed
          h._ref_t == h._ref_t       True      True  passed
           h._ref_t < h._ref_t      False     False  passed
       h._ref_t == v._ref_x[0]      False     False  passed
           h.x[1] == h.x[1][0]      False     False  passed
          h.xpanel == h.xpanel       True      True  passed
          h.xpanel == h.xvalue      False     False  passed
            h.xaxis == g.xaxis      False     False  passed
            g.xaxis == g.xaxis       True      True  passed
           g.xaxis == g2.xaxis      False     False  passed

* bugfix to comparisons to distinguish between h.x[2] and h.y[2]

* cleaner error handling for attempting to test inequality of arrays.

Previously for multidimensional array h.x, attempting
h.x[2] < h.x[1] would raise a SystemError because an
error was indicated by the tp_richcompare returning NULL
but no error condition was set. It now correctly raises a
TypeError by invoking Py_RETURN_NOTIMPLEMENTED

* consistent TypeError exception for incomparables in Python 2 and 3

This was necessitated because Py_RETURN_NOTIMPLEMENTED is only
defined for Python 3, and attempts to implement it just caused more
calls to richcompare.

example:

>>> h('double x[4][4]')
1
>>> h.x[2] < h.x[3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: this comparison is undefined
>>>

* more comparison fixes

HocArrayIncomplete now treated like HocArray
objects of different type can only be compared for == or !=
HocArrays that belong to NEURON objects (e.g. Vector) now compare the objects too