Show full path compiled MOD files.
Prior to this commit the output on failure would be:

    [ 78%] Built target hoc_module
    hhwatch.cpp: In function ‘void _hoc_destroy_pnt(void*)’:
    hhwatch.cpp:175:61: error: cannot convert ‘DatumHandle’ {aka ‘neuron::container::Mechanism::DatumHandle’} to ‘Datum*’ {aka ‘neuron::container::generic_data_handle*’}

which isn't helpful because it's not obvious which `hhwatch.cpp`
contains the faulty code.