Mac OS CI get stuck with Python 3.6, 3.8 and 3.9. If we cancel stuck build then we see:
    + nrniv -python -c 'import neuron; neuron.test(); quit()'
    Warning: no DISPLAY environment variable.
    --No graphics will be displayed.
    NEURON -- VERSION 8.0a-712-g5db9e33e3 HEAD (5db9e33e3) 2021-10-20
    Duke, Yale, and the BlueBrain Project -- Copyright 1984-2021
    See http://neuron.yale.edu/neuron/credits

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'neuron'

And after cancelling the job continues until it gets killed.
It seems like with system python somehow gets selected wrong
but not sure how this is possible because we are virtual env
and everything seems to be the same.

Try passing -pyexe explivitly