More cmake cleanup (#260)
* More fixes for windows build. Some are temporary ones.

It now builds till nrniv.so:

kumbhar@DESKTOP-A627701 MSYS ~/nrn/build
$ make
[  6%] Built target nocmodl
[  9%] Built target modlunit
Scanning dependencies of target nrniv_lib
[  9%] Building C object src/nrniv/CMakeFiles/nrniv_lib.dir/__/oc/cygwinprt.c.obj
[ 10%] Linking CXX shared library libnrniv.so
CMakeFiles/nrniv_lib.dir/__/nrnoc/init.c.obj: In function `hoc_last_init':
C:/msys64/home/kumbhar/nrn/src/nrnoc/init.c:351: undefined reference to `modl_reg'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/nrniv/CMakeFiles/nrniv_lib.dir/build.make:6422: src/nrniv/libnrniv.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:181: src/nrniv/CMakeFiles/nrniv_lib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

* Additional windows fixes:
  - find termcap before adding nrniv folder
  - do not link to libdl on mingw platform

* Added missing dependency rules

* CMake cleanup (wip)

dynamic mpi builds are currently broken and need to be looked at again.
This is is due to reorganization of cmake_cnofig/CMakeLists.txt and
cmake/ConfigFileSetting.cmake

* Fixed outstanding issue with cmake config files

* Moved nrnivmodl makefile generator to right dir.

Also did some more cleanup.