consistent TypeError exception for incomparables in Python 2 and 3
This was necessitated because Py_RETURN_NOTIMPLEMENTED is only
defined for Python 3, and attempts to implement it just caused more
calls to richcompare.

example:

>>> h('double x[4][4]')
1
>>> h.x[2] < h.x[3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: this comparison is undefined
>>>