Prevent user from declaring variables and functions with same name (#1992)
* Today use can "declarae" a variable in NEURON block and
  then PROCEDURE or FUNCTION with the same name. For example,
  below doesn't raise any error today:

   ```python
   NEURON {
       SUFFIX glia
       RANGE alfa
   }

   FUNCTION alfa(v(mV)) {
       alfa = exp(v)
   }
   ```

* The reason this works is that the `RANGE alfa` declaration in
  NEURON block id not complete (i.e. variable needs to be "defined"
  in a block like ASSIGNED, PARAMETER etc) and hence doesn't appear
  anywhere in the generated code. If we try to use `alfa` as variable
  then that is a warning and resulted in a compilation error.

* This behavior kind of works but is error-prone. Apart from corner cases
  and confusing behavior, it's difficult to do certain analysis that
  we would like to do (e.g. in new NMODL code generation).

* So for robustness and simplicity, we now throw an error if the user
  try to declare variables and functions with the same name.

  ```console
   $ ./bin/nocmodl mod_x/test.mod
       Translating mod_x/test.mod into mod_x/test.cpp
       Error: alfa used as both variable and function in file mod/test.mod
  ```

* make clang-format happy; update test repos with necessary fixes